### ISSUE TITLE
Stater kit Template Error

### ISSUE THREAD

**Issue by xtwoend** [laravel-indonesia/lentera#39]
Setelah saya donwload dan coba ternya panyak part dari bagian html hilang, dan munkin untuk kedepan gimana kalau menggunakan Gulp untuk dev, seperti yang di pakai laravel 5  masalahnya untuk grunt terlalu sulit untuk orang awam seperti saya, dan ketegantungan terhadap ruby.

**Comment by mul14** [comment]
Btw, ini beres ya? Elixir memang menggunakan Gulp.
