### ISSUE TITLE
use minimum php 5.5, yes or no?

### ISSUE THREAD

**Issue by veelasky** [laravel-indonesia/lentera#47]
[PHP 5.5 features](http://php.net/manual/en/migration55.new-features.php)

set minimum requirement to php 5.5

**Comment by ahmadkarlam** [comment]
Yes

**Comment by reyhansofian** [comment]
apakah pertimbangannya menggunakan PHP 5.5?

**Comment by veelasky** [comment]
ya itu yg ada di feature tsb kelebihanya, untuk prakteknya di laravel nantinya lebih ke defining model relationship lebih enak, pake `::class` class name resolution

```php
use \App\Entities\Group\Group;
use \Illuminate\Database\Eloquent\Model;

class User extends Model {
     ....

     public function group()
     {
            return $this->belongsToMany(Group::class, 'group_user', 'user_id', 'group_id')
     }
     ....
}
```

dan lagipun, **why not?** php 5.5 juga sudah mature.

**Comment by mul14** [comment]
Saya setuju kalau pakai PHP 5.5. Salah satu pertimbangannya ini http://php.net/supported-versions.php. PHP 5.4, pada September (6 bulan lagi) habis masa support-nya. 

Dan Linux distribution populer seperti Ubuntu 14.04 sudah pakai PHP 5.5. Tinggal menunggu waktu saja distro lain yang umum digunakan untuk server akan upgrade default package-nya ke 5.5.

**Comment by AndreMyid** [comment]
Saya sepakat dengan om @mul14. Mungkin yang jadi pertannyaan berikutnya adalah, jika ada yang mau test ke hosting dengan PHP 5.4 apakah berpengaruh/berdampak besar? Haruskah merubah dulu ke PHP 5.4 atau mungkin ada setingan tertentu?

**Comment by mul14** [comment]
Kalau nggak pakai fitur yang ada di PHP 5.5+ yaa nggak ada masalah di PHP 5.4. Misalnya seperti sudah dicontohkan diatas menggunakan `::class`.

**Comment by veelasky** [comment]
resolved
